-- =============================================================
-- RouteWise — MVP Database Schema
-- 001_create_tables.sql
-- =============================================================

-- Required extensions
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -------------------------------------------------------
-- 🟦 FOUNDATIONAL REFERENCE DATA
-- Geographic reference data that rarely changes.
-- Seeded once from verified public sources.
-- -------------------------------------------------------

-- Indian states and union territories with boundary polygons.
-- Schema supports all 36 states/UTs. The boundary column is nullable
-- to allow incremental loading — states without boundary data can
-- still be referenced by name/code for display and future expansion.
CREATE TABLE states (
    id              SERIAL PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE,
    code            VARCHAR(10) NOT NULL UNIQUE,
    boundary        geometry(MultiPolygon, 4326),
    constraints     JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_states_boundary ON states USING GIST (boundary);

-- -------------------------------------------------------
-- 🟨 EXTERNALLY SOURCED DATA
-- POIs discovered from verified external APIs.
-- Always traceable to a source provider and ID.
-- -------------------------------------------------------

-- Cached points of interest with verified geographic data
CREATE TABLE pois (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name            VARCHAR(255) NOT NULL,
    source_id       VARCHAR(255),
    source_provider VARCHAR(50),
    location        geometry(Point, 4326) NOT NULL,
    category        VARCHAR(50) NOT NULL,
    state_code      VARCHAR(10) REFERENCES states(code),
    opening_hours   JSONB,
    metadata        JSONB,
    verified_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_pois_location ON pois USING GIST (location);
CREATE INDEX idx_pois_category ON pois(category);
CREATE INDEX idx_pois_state ON pois(state_code);
CREATE INDEX idx_pois_source ON pois(source_provider, source_id);

-- POI categorization tags
CREATE TABLE poi_tags (
    poi_id          UUID NOT NULL REFERENCES pois(id) ON DELETE CASCADE,
    tag             VARCHAR(50) NOT NULL,
    PRIMARY KEY (poi_id, tag)
);

CREATE INDEX idx_poi_tags_tag ON poi_tags(tag);

-- -------------------------------------------------------
-- 🟧 EXTERNALLY GENERATED ROUTE DATA
-- Route calculations from external routing providers.
-- Cached to avoid redundant API calls.
-- Schema is fully provider-agnostic.
-- -------------------------------------------------------

CREATE TABLE routes (
    id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Origin and destination coordinates (provider-agnostic)
    origin_point      geometry(Point, 4326) NOT NULL,
    destination_point geometry(Point, 4326) NOT NULL,
    origin_name       VARCHAR(255),
    destination_name  VARCHAR(255),

    -- Route computation results (standardized across providers)
    polyline          geometry(LineString, 4326),
    distance_km       NUMERIC(8, 2),
    duration_minutes  INT,
    vehicle_type      VARCHAR(20) NOT NULL,

    -- Intermediate waypoints (provider-normalized JSON array)
    -- Format: [{ "lat": number, "lng": number, "name": string? }, ...]
    waypoints         JSONB,

    -- Provider traceability
    source_provider   VARCHAR(50) NOT NULL,
    source_metadata   JSONB,

    -- Cache management
    fetched_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at        TIMESTAMPTZ
);

CREATE INDEX idx_routes_origin ON routes USING GIST (origin_point);
CREATE INDEX idx_routes_destination ON routes USING GIST (destination_point);
CREATE INDEX idx_routes_provider ON routes(source_provider);
CREATE INDEX idx_routes_fetched ON routes(fetched_at);

-- -------------------------------------------------------
-- 🟩 USER-CREATED TRIP DATA
-- Generated by the trip-planning pipeline.
-- Owned by the user session / account.
-- -------------------------------------------------------

CREATE TABLE trips (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id         UUID,
    trip_type       VARCHAR(30) NOT NULL,
    vehicle_type    VARCHAR(20) NOT NULL,
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    origin_name     VARCHAR(255) NOT NULL,
    origin_point    geometry(Point, 4326) NOT NULL,
    destination_name VARCHAR(255),
    destination_point geometry(Point, 4326),
    route_id        UUID REFERENCES routes(id),
    status          VARCHAR(20) NOT NULL DEFAULT 'draft',
    llm_narrative   JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_trips_status ON trips(status);

CREATE TABLE trip_days (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    trip_id             UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    day_number          INT NOT NULL,
    date                DATE NOT NULL,
    total_driving_km    NUMERIC(8, 2),
    total_driving_minutes INT,
    day_summary         TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(trip_id, day_number)
);

CREATE TABLE trip_stops (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    trip_day_id     UUID NOT NULL REFERENCES trip_days(id) ON DELETE CASCADE,
    poi_id          UUID REFERENCES pois(id),
    stop_order      INT NOT NULL,
    stop_type       VARCHAR(30) NOT NULL,
    arrival_time    TIME,
    departure_time  TIME,
    duration_minutes INT,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(trip_day_id, stop_order)
);
